-- 已部署站点升级到「第三轮：首页 sorher 式区块」时，写入默认首页区块数据
-- 用法：npx wrangler d1 execute wanxu_cms --remote --file=db/seed-home-sections.sql
-- 注意：本文件仅用于老库升级；全新部署请直接执行 db/seed.sql

INSERT OR IGNORE INTO home_sections (id, key, title_zh, title_en, eyebrow_zh, eyebrow_en, items, content_zh, content_en, image, config, sort_order, is_active) VALUES
(1, 'hero', '晚叙 · 仿真植物美学', 'WANXU', '', '', '[]', '精选商品', 'Featured Products', '', '{"cta_link":"/products"}', 0, 1),
(2, 'categories', '特色商品', 'Featured Products', 'Feature Products', 'Feature Products', '[]', '', '', '', '{"category_ids":[]}', 1, 1),
(3, 'services', '服务项目', 'Services', 'Services', 'Services', '[{"title_zh":"家居装饰","title_en":"Home Decor","subtitle_zh":"客厅与商业空间整体美陈","subtitle_en":"Full styling for living & commercial spaces","image":"/images/samples/svc-decor.jpg","url":"/contact"},{"title_zh":"花艺设计","title_en":"Floral Design","subtitle_zh":"仿真花艺与节庆美陈方案","subtitle_en":"Faux floral & festive display schemes","image":"/images/samples/svc-floral.jpg","url":"/contact"},{"title_zh":"空间布置","title_en":"Interior Arrangement","subtitle_zh":"绿植墙与垂直绿化设计","subtitle_en":"Green walls & vertical garden design","image":"/images/samples/svc-interior.jpg","url":"/contact"},{"title_zh":"微景观定制","title_en":"Terrarium Studio","subtitle_zh":"玻璃瓶景个性定制","subtitle_en":"Custom-made glass terrariums","image":"/images/samples/svc-terrarium.jpg","url":"/contact"}]', '', '', '', '{"button_text_zh":"了解更多","button_text_en":"Learn More","button_link":"/contact"}', 2, 1),
(4, 'brands', '品牌一览', 'Our Brands', 'Brands', 'Brands', '[{"title_zh":"阿特利尔绿植","title_en":"ATELIER VERT","subtitle_zh":"","subtitle_en":"","image":"","url":""},{"title_zh":"花漾生活","title_en":"Flora+","subtitle_zh":"","subtitle_en":"","image":"","url":""},{"title_zh":"纳图拉","title_en":"NATURA","subtitle_zh":"","subtitle_en":"","image":"","url":""},{"title_zh":"植物实验室","title_en":"BOTANIC LAB","subtitle_zh":"","subtitle_en":"","image":"","url":""},{"title_zh":"常青工坊","title_en":"EVERGREEN & CO.","subtitle_zh":"","subtitle_en":"","image":"","url":""},{"title_zh":"橄榄屋","title_en":"OLIVE HOUSE","subtitle_zh":"","subtitle_en":"","image":"","url":""}]', '', '', '', '{"watermark":"WANXU"}', 3, 1),
(5, 'store', '厂家资讯', 'Our Factory', 'FACTORY DIRECT', 'FACTORY DIRECT', '[]', '<p><strong>工厂地址</strong></p><p>广东省东莞市绿色产业园 A 栋（自有厂房 8000㎡，欢迎预约参观）</p><p><strong>接待时间</strong></p><p>周一至周六 9:00 - 18:00（GMT+8）</p><p>支持 OEM / ODM 定制，样版间现场选样</p>', '<p><strong>Factory Address</strong></p><p>Building A, Green Industrial Park, Dongguan, Guangdong, China — 8,000㎡ owned facility, visits by appointment</p><p><strong>Reception Hours</strong></p><p>Monday to Saturday, 9:00 - 18:00 (GMT+8)</p><p>OEM / ODM customization welcomed, sample room open for selection</p>', '/images/samples/store.jpg', '{"button_text_zh":"立即询盘","button_text_en":"Send Inquiry","button_link":"/contact"}', 4, 1);
